version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=people
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: build
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgres://postgres:postgres@postgres:5432/people?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432", "--", "/app/start.sh"]
    command: ["./main"]